name: Build and Push Image

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"

env:
  version: 9.0.${{github.run_number}}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=pr
            type=raw,value=${{ env.version }},enable=${{ github.ref == 'refs/heads/main'}}

      - uses: actions/checkout@v4

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: src/
          file: src/ES.Kubernetes.Reflector/Dockerfile
          cache-to: type=gha,mode=min
          cache-from: type=gha
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
