name: Delete PR Package

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr-id:
        type: number
        required: true
        description: Number of the PR whose image should be deleted

jobs:
  delete-package:
    name: Delete PR Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - id: get-version-id
        run: |
          VERSION_ID=$(gh api '/orgs/kflow-ai/packages/container/kubernetes-reflector/versions' | jq '.[] | select(.metadata.container.tags | any(index("pr-${{inputs.pr-id || github.event.pull_request.number }}"))) | .id')
          echo "VERSION_ID=$VERSION_ID" >> $GITHUB_OUTPUT

      - uses: actions/delete-package-versions@v5
        if: steps.get-version-id.outputs.VERSION_ID != ''
        with:
          package-name: kubernetes-reflector
          package-type: container
          package-version-ids: ${{ steps.get-version-id.outputs.VERSION_ID }}
