name: Renovate

on:
  schedule:
    - cron: '0 5 * * *' # daily at 5am UTC
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.22
        with:
          token: ${{ secrets.ES_GITHUB_PAT }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
