name: Renovate

on:
  schedule:
    - cron: '0 5 * * *' # daily at 5am UTC
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          token: ${{ secrets.ES_GITHUB_PAT }}
