name: Stale

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual triggering

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # General behavior
          stale-issue-message: >
            Automatically marked as stale due to no recent activity. 
            It will be closed if no further activity occurs. Thank you for your contributions.
          close-issue-message: >
            Automatically closed stale item.
          stale-pr-message: >
            Automatically marked as stale due to no recent activity. 
            It will be closed if no further activity occurs. Thank you for your contributions.
          close-pr-message: >
            Automatically closed stale item.

          days-before-stale: 14
          days-before-close: 14

          # Labels
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'

          exempt-issue-labels: 'pinned,security,[Status] Maybe Later'
          exempt-pr-labels: 'pinned,security,[Status] Maybe Later'

          # Limits
          operations-per-run: 30